openapi: "3.0.2"
info:
  title: News Comparison API
  description: API to compare how news sources report on a story. Powered by NewsAPI.org https://newsapi.org/
  version: "1.0"
servers:
  - url: https://api.server.test/v1
components:
  schemas:
    Error:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  responses:
    UnauthorizedError:
      description: API Key is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
paths:
  /newsSearch:
    get:
      summary: Search for articles from a range of UK sources
      security:
        - ApiKeyAuth: []
      parameters:
        - name: q
          in: path
          required: true
          description: Query param
          schema:
            type: string
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: object
                properties:
                  articles:
                    type: array
                    items:
                      type: object
                      properties:
                        source:
                          type: string
                        headline:
                          type: string
                        url:
                          type: string
                        imageUrl:
                          type: string
        "400":
          description: Bad Request. User input is invalid 'q' must be specified in the path
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "405":
          description: Method not allowed this endpoint only supports GET requests
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "429":
          description: Too many requests access to this service is being throttled. Please wait and then try again
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: There is an unexpected error on the server side.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "502":
          description: There is an invalid response from an upstream server.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "504":
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
